### PR TITLE
fix sometimes sessions not being saved

### PR DESCRIPTION
**Pull request by RevealedSoulEven**

### CODE REVIEW

**Comment by RevealedSoulEven** [comment]
Fixed #289

**Comment by adrcotfas** [comment]
Hey, how did you reproduce this before the fix?

**Comment by RevealedSoulEven** [comment]
In my phone it was at a condition where only one out of every five sessions were being saved so I didn't knew how to fix that so I have added option where whenever a session and it will create a text file and add the timestamp in it so I used to manually add everything. So I didn't need to reproduce that because it was already happening with me but if you try in any emulator like BlueStack and all so if you try with 10 to 20 session after sometime it won't save means after 10 to 20 sessions it won't start saving those things so this is how I have used frida to analyse what was happening and that function was giving an error and using reverse engineering I got that this was the error and I fix that now it is working I have tested is very well so I have greater this work please merge and thank you.

**Comment by RevealedSoulEven** [comment]
Well, thanks for it. Will add more features too soon

**Comment by adrcotfas** [comment]
@RevealedSoulEven Thank you for your contribution! This will come in version 2.5.6.

Although I was not able to reproduce this issue and don't see the relation between it and the change, the line you removed was redundant at best or affecting the performance in the worst case: https://medium.com/androiddevelopers/room-coroutines-422b786dc4c5.

> Room calls the `CoroutinesRoom.execute` suspend function, which switches to a background dispatcher

**Comment by RevealedSoulEven** [comment]
Yes, that's what I analyzed in Frida.

**Pull request merged**
